version: '3'

services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tinpenny_root
      - POSTGRES_PASSWORD=tinpenny_password
      - POSTGRES_DB=tinpenny
    ports:
      - "55432:5432"
  redis:
    image: "redis:alpine"
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
      - ~/.aws/:/root/.aws:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - AWS_PROFILE=default
      - DEBUG=1
      - SECRET_KEY=foobar
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=tinpenny
      - SQL_USER=tinpenny_root
      - SQL_PASSWORD=tinpenny_password
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
  celery:
    build: ./app
    command: celery -A TinPennyBackend worker -l info
    volumes:
      - ./app:/code
      - ~/.aws/:/root/.aws:ro
    depends_on:
      - db
      - redis
    environment:
      - AWS_PROFILE=default
      - DEBUG=1
      - SECRET_KEY=foobar
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=tinpenny
      - SQL_USER=tinpenny_root
      - SQL_PASSWORD=tinpenny_password
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres

volumes:
  postgres_data: